# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFrameworkMj_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFrameworkMj_ios
	pod 'CocoaLumberjack/Swift'
end

target 'MyFrameworkMj_mac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFrameworkMj_mac
	pod 'CocoaLumberjack/Swift'
end

target 'MyFrameworkMj_tv' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFrameworkMj_tv

end
