# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/MohamedJaffer-24/MyFrameworkMj.git'

source 'https://github.com/CocoaPods/Specs.git'
target 'iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS
	pod 'MyFrameworkMj'
end
